version: '3.4'

services:

  redis:
    ports:
      - "5379:6379"

  zipkin:
    ports:
      - "5411:9411"

  sqlserver:
    volumes:
      - seserver-sqlserver:/var/opt/mssql
    environment:
      - SA_PASSWORD=JWmTjvNnRfKcjvLo0r
      - ACCEPT_EULA=Y
    ports:
      - 1433:1433
      
  seq:
    restart: unless-stopped
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  dapr-placement:
    command: ["./placement", "-port", "50000", "-log-level", "debug"]
    ports:
      - "50000:50000"

  seserver-auth:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5101:80"
      - "50001:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  seserver-auth-dapr:
    command: ["./daprd",
      "-app-id", "seserver-auth",
      "-app-port", "80",
      "-components-path", "/components",
      "-config", "/configuration/seserver-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"
      
  seserver-statements:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5102:80"
      - "50002:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  seserver-statements-dapr:
    command: ["./daprd",
      "-app-id", "seserver-statements",
      "-app-port", "80",     
      "-placement-host-address", "placement:50000",
      "-components-path", "/components",
      "-config", "/configuration/seserver-config.yaml"
      ]
    volumes:
      - "./dapr/components/:/components"
      - "./dapr/configuration/:/configuration"   

  seserver-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5104:80"
      - "50004:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

volumes:
  seserver-sqlserver:
    external: false



