version: '3.4'

services:

  redis:
    image: redis:latest
    container_name: redis
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver

  zipkin:
    image: openzipkin/zipkin-slim:latest
    container_name: zipkin

  seq:
    image: datalust/seq:latest
    container_name: seq

  dapr-placement:
    image: daprio/dapr:latest
    container_name: dapr-placement

  seserver-auth:
    image: ${DOCKER_REGISTRY-}seserverauth
    container_name: seserver-auth
    build:
      context: .
      dockerfile: src/services/SEServer.Auth/SEServer.Auth/Dockerfile
    depends_on:
      - sqlserver
      - seq

  seserver-auth-dapr:
    image: daprio/daprd:latest
    container_name: seserver-auth-dapr
    network_mode: "service:seserver-auth"
    depends_on:
      - seserver-auth

  seserver-statements:
    image: ${DOCKER_REGISTRY-}seserverstatements
    container_name: seserver-statements
    build:
      context: .
      dockerfile: src/services/SEServer.Statements/SEServer.Statements/Dockerfile
    depends_on:
      - sqlserver
      - seq

  seserver-statements-dapr:
    image: daprio/daprd:latest
    container_name: seserver-statements-dapr
    network_mode: "service:seserver-statements"
    depends_on:
      - seserver-statements

  seserver-gateway:
    image: ${DOCKER_REGISTRY-}seservergateway
    container_name: seserver-gateway
    build:
      context: .
      dockerfile: src/gateway/SEServer.Gateway/Dockerfile
    depends_on:
      - seserver-statements
      - seserver-auth